### ISSUE TITLE
Site Down? "Error: localtunnel server returned an error, please try again"

### ISSUE THREAD

**Issue by yuvilio** [defunctzombie/localtunnel#68]
Site itself returning  a [502 Bad Gateway](http://localtunnel.me/)

Tunneling doesn't seem working either. 
```bash
$ lt --port 3000 

Error: localtunnel server returned an error, please try again
    at Request._callback (/home/yuvilio/.nvm/v0.10.33/lib/node_modules/localtunnel/client.js:205:27)
    at Request.self.callback (/home/yuvilio/.nvm/v0.10.33/lib/node_modules/localtunnel/node_modules/request/main.js:122:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/yuvilio/.nvm/v0.10.33/lib/node_modules/localtunnel/node_modules/request/main.js:655:16)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/yuvilio/.nvm/v0.10.33/lib/node_modules/localtunnel/node_modules/request/main.js:617:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
$ 

```

**Comment by defunctzombie** [comment]
yes, been having some issues lately. Back up now.

**Comment by yuvilio** [comment]
working great.  Thanks!
